### PR TITLE
Oauth testing complete

### PR DESCRIPTION
**Pull request by wanderlust-create**
Add spec/features/request/new_google_user_spec.rb
update Gemfile
create basic views:
-welcome/index
-welcome/error
-users/new
-users/show
Add flash_message to views/layouts/application_controller
Add error_message to app/concerns/application_controller

### CODE REVIEW

**Comment by markertmer** [comment]
@wanderlust-create I was not able to get this to work, it was telling me to run bundle install, but when I did it kept giving me the same error message:
image

**Comment by markertmer** [comment]
Also @wanderlust-create , there is a save_and_open_page you left in one of the tests.

**Comment by markertmer** [comment]
One more thing with this: There are like 54 files that were changed. It looks like you ran Rubocop to fix code across the whole repo, but that could make it hard to pinpoint this or any other issues. I recommend undoing the Rubocop commit(s) and just keeping the Oauth testing on this branch. If we can get that to pass, then we can try using Rubocop on another branch later.

**Comment by wanderlust-create** [comment]
I believe the issue @markertmer might be an environmental problem. When I run the tests on my end they are all passing except for the User Model test. 
I suspect it might be the way I wrote the tests because I used the syntax: page.should have_content (how it was written in the example I was following)
instead of: expect(page).to have_content. 
I updated the tests and hopefully, that fixes the problem. 

I also added the User Model test as it was not passing:
-updated the Gemfile to add  gem 'shoulda-matchers'
-updated Gemlock ^^
-added the User Model validation testing to check for name, email (with uniqueness)

**Comment by wanderlust-create** [comment]
image
I am getting this warning and have looked at the sites. Not sure that it's worth spending the time on it right now.

**Comment by wanderlust-create** [comment]
Currently, the conflicts are related to the environment. We need to all compare what gems we are using and have matching Gemfile, rspec_helper, and rails_helper files.

**Comment by wanderlust-create** [comment]
In regards to the Rubocop, you are correct I should have done it in another branch. I learned in. my last project it's best to do it in the beginning and run it as you go to avoid possible issues. As a team, we should have done it at set-up. Or we can all use the gem Erin does that shows the problems as you go. I apologise for running it in the branch.

**Pull request closed without merging**
